### ISSUE TITLE
Title are no more in the header bar

### ISSUE THREAD

**Issue by frodrigo** [teritorio/clearance-frontend#85]
![image](https://github.com/teritorio/clearance-frontend/assets/1785486/b7c0db41-6cb0-435b-b269-aa6b18296dc2)

![image](https://github.com/teritorio/clearance-frontend/assets/1785486/70cb42ca-a6f9-44c1-a83f-8a53ad7df3d3)

**Comment by wazolab** [comment]
That was a subject I wanted to talk about.
I'm not sure that the Header is the right place for this kind of information.
Do you think we are breaking or changing some habits by having it in the page body instead of Header ?

Plus, this part is the same as ProjectLight (which is in fact the Project header, we could rename it)
<img width="1440" alt="Screenshot 2024-04-26 at 09 33 41" src="https://github.com/teritorio/clearance-frontend/assets/38253764/408c96e0-362c-4b8c-b5da-40e9ec568c62">

My thoughts are :
- Rename ProjectLight to ProjectHeader.
- Use ProjectHeader on Changes Log page
